### ISSUE TITLE
IEC Commodore Diskdrive port lacking pull-ups

### ISSUE THREAD

**Issue by gardners** [micro-FPGA/MEGA65-Hacks#2]
SER_CLK, SER_DATA, SER_SRQ require pull-ups.

I need to confirm, but I believe RESET and ATN do not require pull-ups.

**Comment by gardners** [comment]
This is the port that 1541s etc connect to.

**Comment by AnttiLukats** [comment]
R3
- added note close to J6: "IEC 1541 style Diskdrive
- added pullup on signals: SER_SRQ, SER_DATA, SER_CLK

NOTE there are pullups in the drive, but there is still a problem if no drive connected as then low levels are seen from the drive connector

**Comment by AnttiLukats** [comment]
done in R3
