### ISSUE TITLE
Audio jack pin out wrong, sound is very quiet

### ISSUE THREAD

**Issue by gardners** [micro-FPGA/MEGA65-Hacks#4]

**Comment by AnttiLukats** [comment]
fixed schematic, it was really bad bad issue. Working design was copied, and then fixed by PCB engineer looking at pin numbers only.

**Comment by gardners** [comment]
Will this make it also louder? We are doing some testing here with a cable to re-order the pins, but the sound level is still very quiet.

Would the Nexys4's audio output circuit be better?

**Comment by gardners** [comment]
Just checked: The Nexys4 circuit which we also have in the portable MEGA65 prototype is also too quiet, although not as quiet. I think we need a louder audio output circuit.

**Comment by gardners** [comment]
I'll make a separate issue for the loudness, since this one is closed on the basis of fixing the pinout.
